### ISSUE TITLE
FileNotFoundException when run hadoop mapreduce

### ISSUE THREAD

**Issue by flamingofugang** [rdfhdt/hdt-mr#3]
Hi,

I used maven the compile the code, here are the maven hadoop dependencies:
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-common</artifactId>
      <version>2.7.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-mapreduce-client-core</artifactId>
      <version>2.6.0</version>
    </dependency>

I created an executable jar, and put the input ntriples file in input folder. Then I run hadoop:
hadoop jar /home/fug2/hdtrdf/hdt-mr/target/hdt-mr-2.0-jar-with-dependencies.jar -i input

I got a warning message:
WARNING: Only one Reducer. Dictionary creation as a single job is more efficient.
and file not found exception error:
Shared section = dictionary/shared
Exception in thread "main" java.io.FileNotFoundException: File hdfs://mesosdev/user/fug2/dictionary/shared does not exist.
        at org.apache.hadoop.hdfs.DistributedFileSystem.listStatusInternal(DistributedFileSystem.java:658)
        at org.apache.hadoop.hdfs.DistributedFileSystem.access$600(DistributedFileSystem.java:104)
        at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:716)
        at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:712)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.listStatus(DistributedFileSystem.java:712)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1485)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1525)
        at org.rdfhdt.mrbuilder.HDTBuilderDriver.loadFromDir(HDTBuilderDriver.java:646)
        at org.rdfhdt.mrbuilder.HDTBuilderDriver.buildDictionary(HDTBuilderDriver.java:382)
        at org.rdfhdt.mrbuilder.HDTBuilderDriver.main(HDTBuilderDriver.java:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

Does anyone know how to fix this?

Best,
Gang

**Comment by flamingofugang** [comment]
I think we need to create the following directories in the hadoop hdfs first:
directory/shared
directory/subjects
directory/objects
directory/predicates
